# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

version: "3.8"

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - backend

  django-web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - backend

networks:
  backend:
